apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  app_key: bWFXb1h3c1N6bWpqZGRVbGppS0lJO/6hYVIQp88eNlA=  # Base64 encoded APP_KEY
  db_username: cm9vdA==  # Base64 encoded root
  db_password: IUBidWdkZWFMM3I=  # Base64 encoded password (!@bugdeaL3r)
  db_root_password: dGVzdF9wYXNzd29yZA==  # Base64 encoded root password
