apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog
  namespace: openshift-gitops
spec:
  project: default

  source:
    repoURL: https://github.com/talhazafarsb/blog.git
    targetRevision: ArgoCD
    path: deployment/

  destination:
    server: https://kubernetes.default.svc
    namespace: blog

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
