apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: php-fpm
          image: php:8.0-fpm
          env:
            - name: APP_NAME
              value: "blog"
            - name: APP_ENV
              value: "local"
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: app_key
            - name: APP_DEBUG
              value: "true"
            - name: APP_URL
              value: "http://blog.test"
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_HOST
              value: "mysql-db"
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: "db_blog"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db_password
          volumeMounts:
            - mountPath: /var/www/html
              name: app-volume
            - mountPath: /etc/php/8.0/fpm/pool.d/www.conf
              subPath: www.conf
              name: php-fpm-config
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: app-volume
            - mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              name: nginx-config
      volumes:
        - name: app-volume
          emptyDir: {}
        - name: php-fpm-config
          configMap:
            name: php-fpm-config
        - name: nginx-config
          configMap:
            name: nginx-config
