version: '3.8'

services:
  blog-php:
    build:
      context: .
      dockerfile: Dockerfile-php
    image: blog-app
    volumes:
      - .:/var/www/blog
    networks:
      - blog-network

  blog-nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: blog-nginx
    depends_on:
      - blog-php
      - blog-db
    volumes:
      - .:/var/www/blog
    ports:
      - "8081:8081"
    networks:
      - blog-network

  blog-db:
    build:
      context: .
      dockerfile: Dockerfile-db
    image: blog-db
    environment:
      MYSQL_ROOT_PASSWORD: '!@bugdeaL3r'
      MYSQL_DATABASE: db_blog
    volumes:
      - blog-db-data:/var/lib/mysql
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  blog-db-data:
