# Use the official PHP image with FPM and Debian base
FROM php:8.0-fpm-buster

# Install system dependencies and PHP extensions
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    git \
    nano \
    unzip \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd zip pdo pdo_mysql \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN groupadd -g 1001 appuser && \
    useradd -r -u 1001 -g appuser appuser


# Set the working directory inside the container
WORKDIR /var/www/blog

# Copy application files into the container
COPY . /var/www/blog

# Set correct permissions for Laravel files
# RUN chown -R appuser:appuser /var/www/blog/storage /var/www/blog/bootstrap/cache /var/www/blog/.env

#RUN chmod -R ugo+w /var/www/blog/storage/ /var/www/blog/bootstrap/cache /var/www/blog/.env && \
#    chgrp -R 0 /var/www/blog/storage/ /var/www/blog/bootstrap/cache /var/www/blog/.env && \
#    chmod -R guo+w /var/www/blog/storage/logs/laravel.log /var/www/blog/bootstrap/cache && \
#    chown -R appuser:appuser /var/www/blog
RUN chmod -R ugo+rw /var/www/blog/storage/framework  /var/www/blog/bootstrap/cache /var/www/blog/storage/logs/ /var/www/blog/.env /var/www/blog/public
#switch user
USER appuser

# Expose port 9000 for PHP-FPM
EXPOSE 9000

CMD ["php-fpm"]
