apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-to-openshift
spec:
  workspaces:
    - name: source
      description: Contains the deployment manifests
  params:
    - name: NAMESPACE
      type: string
      description: The target OpenShift project/namespace
  steps:
    - name: deploy
      image: quay.io/openshift/origin-cli:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        echo "Switching to namespace $(params.NAMESPACE)"
        oc project $(workspaces.source.path)
        echo "Applying manifests from ./deployment/"
        oc apply -f deployment/
