apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: install-dependencies
spec:
  workspaces:
    - name: source
  steps:
    - name: install
      image: docker.io/library/php:8.0-cli
      workingDir: $(workspaces.source.path)
      script: |
        apt-get update && apt-get install -y unzip git curl
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer

        cp .env.example .env
        composer install
        composer fund
        php artisan config:clear
        php artisan key:gen
        php artisan config:cache
