apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: blog-pipeline
spec:
  params:
    - name: repo-url
    - name: revision
      default: "argoCD"
    - name: app-image
    - name: nginx-image
    - name: db-image
    - name: registry-username
    - name: registry-password
  workspaces:
    - name: shared-workspace
    - name: docker-credentials
  tasks:
    - name: clone-repo
      taskRef:
        name: clone-repo
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: repo-url
          value: "$(params.repo-url)"
        - name: revision
          value: "$(params.revision)"

    - name: install-dependencies
      taskRef:
        name: install-dependencies
      runAfter:
        - clone-repo
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: run-tests
      taskRef:
        name: run-tests
      runAfter:
        - install-dependencies
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build-and-push-blog-app
      taskRef:
        name: build-and-push-image
      runAfter:
        - run-tests
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: docker-credentials
          workspace: docker-credentials
      params:
        - name: IMAGE
          value: "$(params.app-image)"
        - name: CONTEXT
          value: "./"
        - name: DOCKERFILE
          value: Dockerfile-app

    - name: build-and-push-blog-nginx
      taskRef:
        name: build-and-push-image
      runAfter:
        - build-and-push-blog-app
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: docker-credentials
          workspace: docker-credentials
      params:
        - name: IMAGE
          value: "$(params.nginx-image)"
        - name: CONTEXT
          value: "./"
        - name: DOCKERFILE
          value: Dockerfile-nginx

    - name: build-and-push-blog-db
      taskRef:
        name: build-and-push-image
      runAfter:
        - build-and-push-blog-nginx
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: docker-credentials
          workspace: docker-credentials
      params:
        - name: IMAGE
          value: "$(params.db-image)"
        - name: CONTEXT
          value: "./"
        - name: DOCKERFILE
          value: Dockerfile-db
