apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-nginx
  labels:
    app: blog-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-nginx
  template:
    metadata:
      labels:
        app: blog-nginx
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: blog-nginx
          image: docker.io/talhazaffar0/blog-nginx:tkn
          ports:
            - containerPort: 8081
          volumeMounts:
            - mountPath: /var/www/blog
              name: blog-app-code
            - mountPath: /var/cache/nginx
              name: nginx-cache
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: blog-app-code
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: blog-nginx
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: blog-nginx
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: blog-nginx-route
spec:
  to:
    kind: Service
    name: blog-nginx
  port:
    targetPort: 8081
  tls:                 # Optional if HTTPS is required
    termination: edge  # Edge termination for HTTPS (remove if not using HTTPS)
